version: "3.9"
services:
  charted:
    image: 10.10.20.200:5000/charted:stg-latest
    networks:
      - edge
    environment:
      - CONVEX_DEPLOYMENT=joyous-guanaco-769
      - CONVEX_SITE_URL=https://joyous-guanaco-769.convex.site
      - 'JWKS=${JWKS}'
      - 'JWT_PRIVATE_KEY_B64=${JWT_PRIVATE_KEY_B64}'
      - NEXT_PUBLIC_CONVEX_URL=https://joyous-guanaco-769.convex.cloud
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=edge
        - traefik.http.routers.charted-stg.rule=Host(`charted.fridaybuilt.com`)
        - traefik.http.routers.charted-stg.entrypoints=web
        - traefik.http.services.charted-stg.loadbalancer.server.port=3000

networks:
  edge:
    external: true
